language: java
jdk: oraclejdk8
sudo: required
dist: trusty
install: true
addons:
  sonarcloud:
    organization: "worksapplications"
    token:
      secure: "JIKI52CkXqNLVn9p9JNb+gNEwJtq2k3lajCjf1g868xkh19kkDNF6wCP3Ni+1AILQlXBRGUzWqCYB9BlXTjBtT5A7pRppCM2Q6JOpKHS8V1RKex0mGZ4pp5IcZMtXO8YX6yILL9PuRezUhdo0aJiasWaL6SGdzeUkGumZLIM6UGNm6qI1eab2YIDKxVnQ5I5tJrJ2owd/kUmFckXREOlmMU3VowjvSnB1ezUqLHnhk2qO+ZHaHc9pO5njA4u+XzGDUypzmb1sgphqQf2Urh0yIwrB2cby/OdjJi4s4n5PDmjOSd1jLmOu9ZJ4Omr7iJJ2ZCF0d00ownOax1jCsM81uyaQYhi+5AEWSmNy/4+PfHpRD4w2uhNS+r9TFWRGVMwmyzENyoIvGObx0tECEB+o0h5yn6RBb5KzVzZlQYl8wQfA3nv3AIx7IkHkWtr/t//nyedpe1WgI1AR+ruAp9xP7vg5YrHKMzpDz9DBY5Q9ypkfv7Vne99kb8r3Ompzt2+XNysp47fR9LqB07WtjkJ6ia0wVsd8bWgADeMp6p5xa+4uwkl9/IXilPzAWQuI229OsskZXx2W6ANv22Vi+6CgrSlxUAtg5k0k7QzcCIp9fk4l5jmaTXJWRkWbsUO1thjr4ecylK1SJsMy9b2FGJNAM2YjD6lONzirI7NC0fTqws="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test -B
after_success:
  - mvn sonar:sonar -B
before_deploy:
  - mvn clean package -B
deploy:
  provider: releases
  api_key:
    secure: "Qst5ZeqRX8wckI5+0mFWBgHFFt2imdczSp4jLjoc/ydi/1aYxDx12Y30x1LWyf5gLuLavDgMxIegIfPATBvrOQysgY0qO5isc0vy6m6BSNXHFJZaWYXdSPBQCA/XCzE2L2s+3B6i4DL5X4e2SI+0DoyDjvXzGf5kH2sOBxkhGTu9C2lkyUiOXWXDkWR4xAnb5UK4KShjP3FtarJrmw82AOs3C5gYfGYI56D97WfQMpHq79hesrgSHW7zFA6IqthSTGEw4qCCnAHQyPE0DDbDAZTcAftjeecsJ5g+hkKy3iwgQDLN6iiM3RB1luqf1Us1ajWvCw88jdiYmGIr9wbivr5yxoi46SEkdZwjw1xSpCze3gRoNGxTnN4BOd/fs7t0BQNphqUHVeLPFu1ib4dnEzB1wNrcMNCJHhupVN4j8mqFIu0QWoDkh0MhRpcRw0tJK6EXnjARjgZ//0hjLqcbZeBgOoglrvkGVyO8G7OncC2ZqxVurxa4h+X5/SN/EicrKcg0gjoJrfVTL6OWzGWJGNQDmeUkcTNnocXn13549bwpEfamKAxCccVRIiZPAOsuDVkEc/Pk2Cfc8uFJ/NG0zVFU4aQCXbSvI9/I4ZAgEJ0WdBcKZNW4DF+jqd+vhpzzWBO0plk3B8huLendZ8whpdrOdJXzgVKsK8exv1nc/HQ="
  file_glob: true
  file: target/releases/*.zip
  overwrite: true
  skip_cleanup: true
  on:
    repo: WorksApplications/elasticsearch-sudachi
    tags: true
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"